version: "3"
services:
  app:
    build: 
      context: ./client
      dockerfile: dev.Dockerfile
    volumes: 
    - ./client:/usr/local/app/
    ports:
    - 80:80
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
    - 3000:3000
    volumes: 
    - ./server:/usr/local/app/